sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf -f Dockerfile.dev .

script:
  - docker run -e CI=true dantedxwolf npm run test

deploy:
  provider: netlify
  site: "piyalhelpingjamil"
  auth: "21b8aa26-eeba-4b27-b1fd-066e803872c1"
  edge: true
  on:
    branch: master